### ISSUE TITLE
Render Plastictool Ubuntu AMD Radeon RX 460 Graphics bad

### ISSUE THREAD

**Issue by Toybulldog** [opentoonz/opentoonz#1096]
Hallo Opentoonz

This is the first time I write in Github-Opentoonz, I would like to introduce myself.
My name is Peter and I live in Germany.
2D animation is relatively new for me and thanks to the open source community grow strongly.

Since I have a new computer, I can use many functions in Opentoonz.
( AMD FX-8370E Eight-Core Processor × 8 ,
  AMD Radeon (TM) RX 460 Graphics,
  64 Bit Ubuntu 16.04 LTS )

I am using Appimage OpenToonz-1.1.2-2017.03.09-3bcfe-64bits

Unfortunately, I have a problem with Plastic tool.
It all worked perfectly except for rendering.
Then these errors occur, as seen in the video.

https://vimeo.com/208018988

About the open driver amdgpu everything has worked very badly to very badly.
When I installed the AMDGPU-Pro Driver version 16.60 for Ubuntu 16.04 has everything, except for the rendering works.

When I create on the vectors colum which works perfectly rendering, see video.

sorry for my bad English

Lg Peter

**Comment by hvfrancesco** [comment]
Yes, there is the same problem on MacOS too. Plastic Tool at present is more or less unusable on Linux and Mac due to this issue, and apparently nobody is working on solving it

**Comment by artisteacher** [comment]
Since multiple OS #856 #1055  are having this issue, hopefully a developer will be able to take this on soon.

**Comment by ideasman42** [comment]
Can someone confirm if this happens with OpenGL drivers from NVidia on Linux?

**Comment by hvfrancesco** [comment]
I have tested on Ubuntu 14.04 (the appimage provided by morevna project) with NVidia, and on Ubuntu 16.04 with Intel integrated GPU, and unfortunately both configurations showed the same rendering issue

**Comment by hvfrancesco** [comment]
the system with NVidia GPU using NVidia proprietary driver

**Comment by ebarranco** [comment]
I have the same  behavior in Manjaro Linux 17 64bits, AMD Radeon HD 5700 series, driver version 15.20.3.

**Comment by jpturcotte** [comment]
Is it related to issue #856?

**Comment by artisteacher** [comment]
This is finally working in OS X with the latest nightly build. Is there still a problem with Ubuntu?

**Comment by Toybulldog** [comment]
Hallo
I have already tried it. Unfortunately I can not install "Opentoonz"
I get the following error message .
![install ot latest nightly build](https://user-images.githubusercontent.com/11164330/35181233-47115aca-fdbe-11e7-9f48-01cd6e35293a.png)

**Comment by Toybulldog** [comment]
Hallo @artisteacher  
@morevnaproject Fix the linux build 
I just got the github 466fc8e4fc6e73d7595e4073f5344952cf3fd53b install ,
and I am the happiest boy in the moment in the world.
The Plastic tool works, until I can see that far.

Thank you very much to all developers
lg peter

**Comment by Toybulldog** [comment]
Hallo @artisteacher

I tested the plastic tool now in peace. 
I can use the plastic tool. I click the eye, OT show me the render pictures, everything is perfect until there.
But if I go under File and click on "Preview" or "Render", "Render to Mp4", the program aborts.
![1](https://user-images.githubusercontent.com/11164330/35263622-d5427402-0019-11e8-9712-4d9be2a83ddd.png)
![2](https://user-images.githubusercontent.com/11164330/35263628-dade3702-0019-11e8-9606-f65331ed91d0.png)
![3](https://user-images.githubusercontent.com/11164330/35263633-e1780d86-0019-11e8-8e9d-a6f25541b8ae.png)

**Comment by artisteacher** [comment]
When I first installed this build I had a good amount of crashing. After removing alias and .webm files from my output location, and removing unnecessary stuff folders before a new install, the crashes which had seemed related to the plastic tool stopped.

If the problem isn't old data or an FFMPEG incompatibility, you should share the full crash report to help the developers figure out what is going wrong.

**Comment by Toybulldog** [comment]
Please watch the video, because you can see the problem
The same I tried, in which I have created complete new folder in ".config".
Unfortunately the same results

![plastic tool crash if render](https://user-images.githubusercontent.com/11164330/35317584-c2422a00-00d7-11e8-87df-b50ffdddfc33.png)

[vimeo.com/252464855](url)

**Comment by flurick** [comment]
Was fixed by #1726
(Rendering crashes aside)

**Comment by RodneyBaker** [comment]
Thanks @flurick 
Will close.

Anyone still having rendering issues with Plastic Tool is encouraged to open a new report with pertinent data if it isn't the same issue as #3999.  If likely the same issue then adding information to that report is preferred.
Thanks!

**Comment by artisteacher** [comment]
I can't trigger the box anymore on my MacBook at home but I think I still get it on occasion on the iMac at school when I'm using a projector.

**Comment by RodneyBaker** [comment]
Closing this as likely resolved although unconfirmed.

Recommend opening a new report with examples, video, project files in order to lock the issue down and target it for resolution.

Recommend referencing this issue in any newly opened report.
