### ISSUE TITLE
High dpi and sub-xsheet results in crash in some rooms

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#1285]
Loading any scene with a sub-xsheet from the startup popup now causes a crash (at least in OS X 10.12.5). Loading scenes with subxsheet directly from the menu (File --> Load Scene) does not result in a crash. The scenes can also be loaded from the file browser, but in that case, changing rooms results in a crash. If a scene with a subxsheet is loaded, "Save Scene As" results in a crash (though the duplicate scene is saved). This is true for both new and previously existing subxsheets.  I do have the xsheet toolbar enabled (love it!!!) - disabling it does not resolve the crashing. The level types don't seem to make a difference.

To reproduce:
From Startup Pop-Up select a recent scene with a subxsheet

**Comment by turtletooth** [comment]
I just tried it on multiple scenes and couldn't reproduce it.

**Comment by artisteacher** [comment]
I'm not having a problem on 10.11.6, so it may be another Sierra specific issue. I'll reinstall and see if that makes a difference. Here's the crash report:

[crash_subx.txt](https://github.com/opentoonz/opentoonz/files/1077577/crash_subx.txt)

**Comment by artisteacher** [comment]
I installed the latest build and restarted the computer. Now the subxsheets are loading without issue.

**Comment by turtletooth** [comment]
What do you think?  Can this be closed?

**Comment by artisteacher** [comment]
It started again, so it should probably stay open for now. My computer is out to be serviced for an unrelated issue but once it is back I'll try a clean install.

**Comment by artisteacher** [comment]
So I've found that it's actually a specific room that I've modified that's having the issue with sub-xsheets. I've played around with different window combinations  and it looks like it might be something to do with the style editor with the xsheet?

To duplicate:
1. Create a new room 
2. Add the xsheet  
3. Add the style editor above the xsheet 
4. Close and reopen OT
5. Load a scene with a sub-xsheet

**Comment by artisteacher** [comment]
I reinstalled some old nightly builds and it looks like this problem started sometime between the April 14th build (which does not crash in Sierra) and the April 24th build (which does crash in Sierra).

**Comment by artisteacher** [comment]
@shun-iwasawa it looks like this crash with the sub-sheet levels in 10.12.5 started after the high dpi support was added - the build from April 21st [https://github.com/opentoonz/opentoonz_nightlies/releases/tag/nightly_039ecc9c2cbbda6dcf1d48a49320e68755a55a59](url) is the first build that causes this crash.

**Comment by artisteacher** [comment]
Changing the resolution to the the lowest possible setting for Sierra (Scaled --> Larger Text) allows me to open the scenes with sub-xsheets without issue (regardless of the room), so it looks like this definitely related to something with the high-dpi and is not a problem specific to Sierra. Leaving the resolution that low, or not using sub-xsheets are not great options. Any assistance would be greatly appreciated!

**Comment by artisteacher** [comment]
Loading the scene works without issue if a window is open fullscreen. I can also open from the Browser room and switch to a problematic room without issue.

I'm including some messages from Console:
<img width="1016" alt="screen shot 2017-07-12 at 11 03 47 pm" src="https://user-images.githubusercontent.com/21159116/28148763-c25053a2-6756-11e7-939e-ddf987b8977e.png">
<img width="1021" alt="screen shot 2017-07-12 at 11 05 43 pm" src="https://user-images.githubusercontent.com/21159116/28148764-c4b1b3d4-6756-11e7-9221-cd184de7f543.png">

**Comment by artisteacher** [comment]
Both the xsheet and style editor must be docked to cause a crash. If either window is floating instead, no crash occurs.

**Comment by artisteacher** [comment]
The Morevna release of OT does not have this issue 🎉

**Comment by turtletooth** [comment]
@morevnaproject Did you do anything different?

**Comment by morevnaproject** [comment]
@turtletooth Morevna Edition 1.1.3 is not the same as official build of 1.1.3. It is uses all commits from master branch up until July 6th - https://github.com/blackwarthog/opentoonz/commits/v1.1.3.0-morevna

So, it looks like this issue is fixed in master branch by @shun-iwasawa or some other team member.

**Comment by artisteacher** [comment]
I just realized it's possible that it's not actually fixed. The moreva release has a bug where the docked style editor is frozen in whichever room is active when opening the app. Since it's frozen, whatever incompatibility between the style editor and sub-xsheets exists on my system must not register.

Since no one else seems to be having this problem, I wonder if my gpu could be part of the problem.

**Comment by artisteacher** [comment]
I think this is actually related to an issue with automatic graphics switching #1439, which explains the inconsistent results. If high-performance graphics are enabled, this is not an issue.

**Comment by artisteacher** [comment]
Closing since I am no longer getting this crash. When I can open OT, there is no longer a problem loading scenes with a sub-xsheet. It is very possible it is working because I have automatic graphics switching turned off.
