### ISSUE TITLE
Fullscreen:  Black combo viewer

### ISSUE THREAD

**Issue by HamousOnWheels** [opentoonz/opentoonz#1692]
Switching to fullscreen with ctrl+` turns the viewer completely black. It can still be captured with screenshot and video tools so i had to take photos. Alt-tabbing makes the viewer visible again but interacting with it turns it back to black. Menus are also invisible in fullscreen.

Tested with 1.2 and OTX 12/5 on windows 7.

![img_20171215_184127569](https://user-images.githubusercontent.com/34580619/34053815-84e8f158-e1c8-11e7-8652-c7022f1ee423.jpg)

![img_20171215_184138662](https://user-images.githubusercontent.com/34580619/34053872-bff9f5f8-e1c8-11e7-84c1-0bc1766371dd.jpg)

**Comment by manongjohn** [comment]
Confirmed this issue.  Oddly, on my laptop monitor it does this, but on second monitor and on my cintiq 12wx, it doesn't.

**Comment by turtletooth** [comment]
Again, this is a qopengl thing.  It works fine on the modified version

**Comment by RodneyBaker** [comment]
This issue should be resolved.
@HamousOnWheels can you confirm?

**Comment by HamousOnWheels** [comment]
Unfortunately I still have the issue on the latest nightly 12/3.

**Comment by RodneyBaker** [comment]
Can you share you computer/system specs
I'll guess Nvidia Graphics on the Windows machine...

Passing strange taht this is being seen on both Mac and Windows in this way.

**Comment by HamousOnWheels** [comment]
You guessed right.
CPU: Ryzen 1600
8 GB RAM
GPU: Nvidia 1050ti, driver version 385.41 (haven't updated these in a while for stability reasons but I can do it if it helps testing)
OS: Windows 7

The specs haven't changed since I first posted the issue.

**Comment by manongjohn** [comment]
Try adding a 3D profile for the OpenToonz executable, set to use high performance GPU in your NVidia settings.

**Comment by HamousOnWheels** [comment]
Already had it, in fact! No change regardless of settings, or if profile is added or removed.
![image](https://user-images.githubusercontent.com/34580619/49398808-c1218580-f73f-11e8-9146-58b1c954df1a.png)

**Comment by RodneyBaker** [comment]
Closing as likely resolved.
@HamousOnWheels Please let us know if you are still experiencing the same or similar problems.

**Comment by HamousOnWheels** [comment]
Did not work on stable 1.3 but confirmed fixed in the latest nightly 10-22.

**Comment by RodneyBaker** [comment]
Thanks for the confirmation.
The v1.3 release (stable) you refer to is likely from January 2019 so it wouldn't have the fix.
The release via the website link is (usually) annual so look for that circa v1.4 release in January 2020.
