### ISSUE TITLE
Tablet not drawing correctly

### ISSUE THREAD

**Issue by MrSoke** [opentoonz/opentoonz#1712]
Not sure if it has already been reported, I couldn't see it, but with the 1.2.0.1 morevna edition appimage whenever I draw a line very quickly it will only draw about half of it way before I actually release the pen from the tablet, this wasn't an issue with version 1.1.3.9

**Comment by morevnaproject** [comment]
Fixed in Morevna Edition 1.2.0.2 by reverting changes of #1659. 

Official OpenToonz still affected. See relevant comment - https://github.com/opentoonz/opentoonz/pull/1659#issuecomment-355832631

**Comment by RodneyBaker** [comment]
Closed this prematurely as I see @morevnaproject 's note about elements of the problem still persisting.

**Comment by RodneyBaker** [comment]
As this report predates fixes immediately after v1.2 and afterword recommend a review.
Recommend closing if additional feedback cannot confirm continuing issues.
