### ISSUE TITLE
OpenToonz 1.2 crash

### ISSUE THREAD

**Issue by pnelson2** [opentoonz/opentoonz#2096]
### Issue Summary
Crash

### Steps to Reproduce
intermittent.   I just downloaded OpenToonz from Github 5 days ago and I've had 5 crashes.  In this case I was inserting a new drawing in my level strip.   I've also had it crash selecting styles.

### Expected Results
I expected a new drawing to be inserted

### Actual Results
Crash  "Unhandled exception at 0x000007FEE566C87C (tnztools.dll) in OpenToonz_1.2.exe: 0xC0000005: Access violation reading location 0x0000000000000080."

### System Information
* 1.2.0 Built Dec11 2017 13:37:39
* Windows 7
* Xeon E3-1240 V2, 3.4 GHz 
* 8G
* NVidia Quadro 600   
* Wacom Intuos 3
[OTCrash1.txt](https://github.com/opentoonz/opentoonz/files/2125773/OTCrash1.txt)

**Comment by manongjohn** [comment]
You are on the original release version of 1.2 which there were some known problems with. It might have been fixed in a nightly later.

I suggest downloading the 1.2.1 RC2 (release candidate No.2) for the official 1.2.1 that is expected to drop next week and see if that helps

**Comment by RodneyBaker** [comment]
@pnelson2 Can you confirm the issue is still present in current releases (v1.3 and/or most recent nightly releases)?

The timeframe of this crashing suggests the crash was related specifically to v1.2 and should no longer be an issue... or at least not the same issue.

**Comment by RodneyBaker** [comment]
Closing pending additional information from @pnelson2
