### ISSUE TITLE
Recent macOS builds crash on startup

### ISSUE THREAD

**Issue by manongjohn** [opentoonz/opentoonz#3748]
Recent macOS Actions (master) and nightly builds crash when starting on 10.15 (Catalina)

For GitHub Actions, it crashes for this:

> Dyld Error Message:
>   Library not loaded: @rpath/libopencv_video.4.5.dylib
>   Referenced from: /Users/xxx/Desktop/OpenToonz.app/Contents/Frameworks/libopencv_gapi.4.5.dylib
>   Reason: image not found

For Nightly, it crashes for this:

> Dyld Error Message:
>   Library not loaded: @executable_path/../Frameworks/EDSDK.framework/Versions/A/EDSDK
>   Referenced from: /Applications/OpenToonz.app/Contents/MacOS/OpenToonz
>   Reason: image not found

**Comment by artisteacher** [comment]
I can't open OT on macOS Big Sur either.

For the Actions builds:
<img width="588" alt="Screen Shot 2021-03-11 at 7 23 36 PM" src="https://user-images.githubusercontent.com/21159116/110873343-89e79a80-829f-11eb-81e1-06d37160f43c.png">

For the latest nightly:
<img width="622" alt="Screen Shot 2021-03-11 at 7 23 58 PM" src="https://user-images.githubusercontent.com/21159116/110873369-97048980-829f-11eb-8695-7ad5f3965ad9.png">

**Comment by shun-iwasawa** [comment]
@manongjohn 
Thank you for the notice. regarding the nightly build, I fixed Jenkins script to copy EDSDK framework so I think the problem is resolved.
OTOH I haven't looked into GitHub Actions artifacts yet. 

@artisteacher 
Thank you for the report. I confirmed that `libImath-2_5.25.dylib` depends on the library in `@rpath` , which should be replaced by the ones in  `@executable_path/../Frameworks` . I'll fix it!

**Comment by shun-iwasawa** [comment]
@artisteacher 
I think all paths in dependency libraries are fixed. @artisteacher can you please try again with the latest nightly? Thanks!

**Comment by artisteacher** [comment]
@shun-iwasawa - it's still crashing, though because of a different library:
<img width="609" alt="Screen Shot 2021-03-13 at 8 26 58 PM" src="https://user-images.githubusercontent.com/21159116/111054408-8a686880-843a-11eb-8988-f109d719ee42.png">

**Comment by shun-iwasawa** [comment]
@artisteacher 
I'm sorry to take the trouble!
Now I (hopefully) modified not only with `@rpath/*` but also every paths. Can you please test the latest nightly again?

**Comment by artisteacher** [comment]
I can open the latest nightly successfully. Actions artifact still crashes.

**Comment by shun-iwasawa** [comment]
@artisteacher 
Fixed the actions artifact. Please try [this version](https://github.com/opentoonz/opentoonz/actions/runs/653235228). Thanks!
