### ISSUE TITLE
Control Point Editor Tool. Incorrect behaviour after using Tape Tool

### ISSUE THREAD

**Issue by Befzz** [opentoonz/opentoonz#4295]
**Describe the bug**
Incorrect behaviour(dragging control point) of Control Point Editor Tool after using Tape tool.  
  
Plus. It crashes sometimes much later while dragging(or mouse_up immidiately after dragging).  
But i cannot reproduce it easily.

**To Reproduce**
1. Vector Layer
2. Zoom in to ~ 10000% (to easily reproduce)
3. Geometric tool -> Polyline -> Make two points
4. Control point editor tool -> change curve shape by dragging the line
5. Tape Tool -> **End Point to End Point + Join Vectors** (not Smooth) -> Connect two points
6. **Drag control point** or Point many times, closer to other point.
7. Curve will start change shape(lean to other control point)
8. **New curves start to behave similar way! No Tape Tool needed!**

**Side notes**
Moving Point(segment?) by arrow keys do not cause this problem(not 100% sure).  
My mouse have high polling rate (1000 hz). So, OS generate many _mouse_move_ messages.

**Expected behavior**
Moving control point should behave like before applying Tape Tool

**Device Information:**
 - OS: Windows 10 x64
 - OpenToonz Version: 1.5 Mar 2022
 - GPU: nvidia 1060
 - GPU Driver Version: 496

https://user-images.githubusercontent.com/1160036/156572287-c69faa1d-008e-4512-87b8-8bbe4025bade.mp4
  

**Before Tape Tool. Control point dragged closer to other many times.**  

![image](https://user-images.githubusercontent.com/1160036/156574023-3b7763a9-0cf8-40a7-b576-91877a9ba3e9.png)

**Tape Tool applyed. Control point dragged closer to other many times.**  

![image](https://user-images.githubusercontent.com/1160036/156572443-735ba4d6-0675-4742-bed3-4e1f8e5254c1.png)

**Comment by RodneyBaker** [comment]
Thanks for the report @Befzz 
@shun-iwasawa described a similar issue with vector bias handles although I don't see that report with a cursory search.
I'll try to remember to reference that when next coming across it.

At any rate, this description appears to align closely with that previously reported problem.

**Comment by RodneyBaker** [comment]
Given the amount of changes to vector graphics in Opentoonz since 2022 it would be good to review this report.

**Comment by RodneyBaker** [comment]
A slightly related problem was (partially) resolved via #2355 although because that solution loses color fill it was never merged into Opentoonz.

**Comment by dbalagansky** [comment]
There is a couple of issues which seem to have some common cause: 
* #4295 (this one)
* #2230
* #4061

I still see something along the lines of [#2230#issuecomment-560537910](https://github.com/opentoonz/opentoonz/issues/2230#issuecomment-560537910), specifically it _feels_ like:
> during prolonged usage of the control point handles

but I don't have a reproducer.
