### ISSUE TITLE
Crash in png_create_read_struct_2 when going to "Custom" tab in Style Browser

### ISSUE THREAD

**Issue by yamisama** [opentoonz/opentoonz#607]
Creating a new vector level and then going to the "Custom" tab in the Style Editor instantly crashes the application. Note that it isn't the main thread that's crashing, but a background thread. My guess would be that it is generating thumbnails in the background.

OpenToonz Version: July 9th nightly
OS: OS X 10.9.5
Can be reproduced multiple times: yes

```
Thread 10 Crashed:: QThread
0   libpng16.16.dylib               0x00000001061ab9ac 0x1061aa000 + 6572
1   libpng16.16.dylib               0x00000001061b31b4 png_create_read_struct_2 + 19
2   libpng16.16.dylib               0x00000001061b319b png_create_read_struct + 27
3   libimage.dylib                  0x0000000103ce55a3 PngReader::open(__sFILE*) + 243
4   libtnzcore.dylib                0x0000000102b727f2 TImageReader::open() + 658
5   libtnzcore.dylib                0x0000000102b72dd7 TImageReaderP::TImageReaderP(TFilePath const&) + 135
6   libtnzcore.dylib                0x0000000102b72e3d TImageReaderP::TImageReaderP(TFilePath const&) + 29
7   libtnzcore.dylib                0x0000000102b7f93c TLevelReader::getFrameReader(TFrameId) + 76
8   libtoonzlib.dylib               0x00000001034f49f8 CustomStyleManager::StyleLoaderTask::run() + 744
9   libtnzcore.dylib                0x00000001029a0e9e TThread::Worker::run() + 286
10  org.qt-project.QtCore           0x0000000105be8d93 0x105bb1000 + 228755
11  libsystem_pthread.dylib         0x00007fff86d23899 _pthread_body + 138
12  libsystem_pthread.dylib         0x00007fff86d2372a _pthread_start + 137
13  libsystem_pthread.dylib         0x00007fff86d27fc9 thread_start + 13
```

**Comment by turtletooth** [comment]
Seems to be Mac related? I can't reproduce it on Windows 10.

**Comment by yamisama** [comment]
Quite possibly. The Mac version is a lot less stable than the Windows version, to the point where it is barely usable. It's probably partly due to the fact that Ghibli uses Windows.

Windows is a lot more forgiving with certain types of errors, such as file handles being closed multiple times and things like that, so the bug might still be there, but not have any major consequences.

I'm afraid I currently can't do a git checkout and do dev work on my machine so I can't run it in a debugger, but that PNG reading code in `PngReader::open()` in looks rather suspicious to me (from `/image/png/tiio_png.cpp`):

```
void open(FILE *file) override {
    try {
      m_chan = file;
    } catch (...) {
      perror("uffa");
      return;
    }

    unsigned char signature[8];  // da 1 a 8 bytes
    fread(signature, 1, sizeof signature, m_chan);
    bool isPng = !png_sig_cmp(signature, 0, sizeof signature);
    if (!isPng) return;

    m_png_ptr = png_create_read_struct(PNG_LIBPNG_VER_STRING, &m_canDelete,
                                       tnz_error_fun, 0);
    if (!m_png_ptr) return;
```

First off, it never checks the file pointer for `nullptr`values before it does the `fread()`. Instead it does a nonsensical `try … catch` that will never have any effect since assigning a pointer to `m_chan` which is of type `FILE*` is pure C code that will never ever throw an exception. Not quite sure what the intention here was.

I don't know what the behavior of `fread` is if the file pointer is null, and it might be platform dependent, so replacing the `try … catch`

**Comment by yamisama** [comment]
That `perror("uffa");` is kind of funny, it's Italian and means something to the effect of "oh come on!!" 😀

**Comment by artisteacher** [comment]
I haven't had this issue with 10.11.6 or 10.12.4. Either the problem is fixed, or it is specific to Mavericks.

**Comment by yamisama** [comment]
Just tested it with a more recent nightly, and it seems that it is indeed gone – but since there was no change to the PNG reader source file, I suspect the problem behind it isn't fixed, it just doesn't get triggered any more.

I think at least the missing null pointer check should be added, and checking the return value of `fread` would also be a good idea, i.e. along these lines (never compiled/tested this):

```
void open(FILE *file) override {
    // This function assumes that it is supplied with an open file
    assert(file != nullptr);

    m_chan = file;

    unsigned char signature[8];
    const std::size_t numBytesRead = fread(signature, 1, sizeof(signature), m_chan);
    if(numBytesRead < sizeof(signature)) return;

    // Return value of 0 indicates that all bytes match
    const bool isPng = (png_sig_cmp(signature, 0, sizeof(signature)) == 0); 
    if (!isPng) return;
```

This removes the nonsensical `try…catch` with that Italian error (same guy as #974?) with an `assert` and adds some error handling for `fread`.

With the original code, it would be conceivable that a file is only four bytes long, but it would still read those four bytes and try to compare the entire `signature` buffer, which is 8 bytes long, to the reference value, including whatever 4 bytes of garbage might be in `signature` from before since it's never zeroed out – possibly even the correct signature bytes from the last file that was opened, in which case it would incorrectly assume it's a valid PNG file and continue to try and read it.

Not sure if this also fixes the original crash, but it should make that code at least a bit more clean/robust.

**Comment by RodneyBaker** [comment]
Closing as likely resolved... although... also noting @yamisama's suggestion that the problem just might not be in a place easily triggered.
